version: '3'

services:
  linkapi:
    container_name: linkapi
    build: '.'
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - linkapi-mongodb
    environment:
      DB_HOST: linkapi-mongodb
    networks:
      - app-connect
    ports:
      - '3333:3333'

  linkapi-mongodb:
    container_name: linkapi-mongodb
    image: mongo
    restart: unless-stopped
    volumes:
      - linkapi-mongodb-data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_DB: ${DB_NAME}
    networks:
      - app-connect
    ports:
      - '${DB_PORT}:${DB_PORT}'

volumes:
  linkapi-mongodb-data:

networks:
  app-connect:
    driver: bridge
